version: '3.8'

services:
  #数据库
  postgres:
    image: postgres:16
    container_name: agentic_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: agentic_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d agentic_db"]
      interval: 10s
      timeout: 5s
      retries: 5